strictness: veryhigh
test-warnings: true

uses:
  - django
  - celery

python-targets:
  - 2
  - 3

requirements:
  - server/requirements.txt

pylint:
  disable:
    - bad-indentation
  options:
    max-args: 10
pep8:
  disable:
    - E111
    - E113
    - E114
    - E121
    - E125
    - E127
    - E129
